version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - VITE_BASE_API_URL =

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
